export default {
  OFW_FW_VER: {id: 0x56, reqFormat: "B", respFormat: "B"},
  OFW_PCB_VER: {id: 0x68, reqFormat: "B", respFormat: "B"},
  QUERY_FW_INFO: {id: 0xA1, reqFormat: "B", respFormat: "pp??"},
  SET_MODE_AGB: {id: 0xA2, reqFormat: "B", respFormat: "B"},
  SET_MODE_DMG: {id: 0xA3, reqFormat: "B", respFormat: "B"},
  SET_VOLTAGE_3_3V: {id: 0xA4, reqFormat: "B", respFormat: "B"},
  SET_VOLTAGE_5V: {id: 0xA5, reqFormat: "B", respFormat: "B"},
  SET_VARIABLE: {id: 0xA6, reqFormat: "BBII", respFormat: "B"},
  ENABLE_PULLUPS: {id: 0xAB, reqFormat: "B", respFormat: "B"},
  DISABLE_PULLUPS: {id: 0xAC, reqFormat: "B", respFormat: "B"},
  GET_VARIABLE: {id: 0xAD, reqFormat: "BBI", respFormat: "I"},
  DMG_CART_READ: {id: 0xB1, reqFormat: "B", respFormat: ""},
  DMG_CART_WRITE: {id: 0xB2, reqFormat: "BIB", respFormat: "B"},
  DMG_CART_WRITE_SRAM: {id: 0xB3, reqFormat: "B", respFormat: "B"},
  DMG_MBC_RESET: {id: 0xB4, reqFormat: "B", respFormat: "B"},
  CART_PWR_ON: {id: 0xF2, reqFormat: "B", respFormat: "B"},
  CART_PWR_OFF: {id: 0xF3, reqFormat: "B", respFormat: "B"},
  CART_QUERY_PWR: {id: 0xF4, reqFormat: "B", respFormat: "B"},
};
