export default {
  ADDRESS : {size : 4, id : 0x00},
  AUTO_POWEROFF_TIME : {size : 4, id : 0x01},
  TRANSFER_SIZE : {size : 2, id : 0x00},
  BUFFER_SIZE : {size : 2, id : 0x01},
  DMG_ROM_BANK : {size : 2, id : 0x02},
  STATUS_REGISTER : {size : 2, id : 0x03},
  LAST_BANK_ACCESSED : {size : 2, id : 0x04},
  STATUS_REGISTER_MASK : {size : 2, id : 0x05},
  STATUS_REGISTER_VALUE : {size : 2, id : 0x06},
  CART_MODE : {size : 1, id : 0x00},
  DMG_ACCESS_MODE : {size : 1, id : 0x01},
  FLASH_COMMAND_SET : {size : 1, id : 0x02},
  FLASH_METHOD : {size : 1, id : 0x03},
  FLASH_WE_PIN : {size : 1, id : 0x04},
  FLASH_PULSE_RESET : {size : 1, id : 0x05},
  FLASH_COMMANDS_BANK_1 : {size : 1, id : 0x06},
  FLASH_SHARP_VERIFY_SR : {size : 1, id : 0x07},
  DMG_READ_CS_PULSE : {size : 1, id : 0x08},
  DMG_WRITE_CS_PULSE : {size : 1, id : 0x09},
  FLASH_DOUBLE_DIE : {size : 1, id : 0x0A},
  DMG_READ_METHOD : {size : 1, id : 0x0B},
  AGB_READ_METHOD : {size : 1, id : 0x0C},
  CART_POWERED : {size : 1, id : 0x0D},
  PULLUPS_ENABLED : {size : 1, id : 0x0E},
  AUTO_POWEROFF_ENABLED : {size : 1, id : 0x0F},
  AGB_IRQ_ENABLED : {size : 1, id : 0x10},
};
